data(iris)
cat("Dimension of the dataset:", dim(iris), "\n")
str(iris)
summary(iris)
cat("Standard Deviation of all features:\n")
sapply(iris[, 1:4], sd)
cat("\n")
by_species <- by(iris[, 1:4], iris$Species, colMeans)
cat("Mean by species:\n")
print(by_species)
cat("Standard Deviation by species:\n")
by(iris[, 1:4], iris$Species, function(x) apply(x, 2, sd))
cat("\n")
quantile(iris$Sepal.Length)
quantile(iris$Sepal.Width)
iris$Sepal.Length.Cate <- cut(iris$Sepal.Length, breaks = quantile(iris$Sepal.Length), labels = FALSE)